move to helpers 2.1

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -3,10 +3,14 @@
 source _common.sh
 source /usr/share/yunohost/helpers
 
+ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M
+
+ynh_app_setting_set_default --key=php_memory_limit --value=64M
+
 #=================================================
 # ENSURE DOWNWARD COMPATIBILITY
 #=================================================
-ynh_script_progression --message="Ensuring downward compatibility..." --weight=1
+ynh_script_progression "Ensuring downward compatibility..."
 
 # Boring backward compatibility
 if [ "${language:-}" == "fr" ] ; then
@@ -15,36 +19,36 @@ else
   language="en_UK"
 fi
 
+# FIXMEhelpers2.1: maybe replace with: ynh_app_setting_set_default --key=password --value="$admin_pwd"
 if [ -z "${password:-}" ]; then
     password="$admin_pwd"
-    ynh_app_setting_set --app=$app --key=password --value="$password"
+    ynh_app_setting_set --key=password --value="$password"
 fi
 
 #=================================================
 # DOWNLOAD, CHECK AND UNPACK SOURCE
 #=================================================
-ynh_script_progression --message="Upgrading source files..." --weight=3
+ynh_script_progression "Upgrading source files..."
 
-ynh_setup_source --dest_dir="$install_dir" --full_replace=1 --keep="local/config/config.inc.php local/config/database.inc.php _data galleries upload"
-ynh_setup_source --dest_dir="$install_dir/plugins/Ldap_Login" --source_id=ldap_plugin --full_replace=1
-ynh_setup_source --dest_dir="$install_dir/plugins" --source_id=log_failed_logins_plugin --full_replace=1
+ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="local/config/config.inc.php local/config/database.inc.php _data galleries upload"
+ynh_setup_source --dest_dir="$install_dir/plugins/Ldap_Login" --source_id=ldap_plugin --full_replace
+ynh_setup_source --dest_dir="$install_dir/plugins" --source_id=log_failed_logins_plugin --full_replace
 
-chmod -R o-rwx "$install_dir"
-chown -R "$app:www-data" "$install_dir"
-
+#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
+#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
 #=================================================
 # PHP-FPM CONFIGURATION
 #=================================================
-ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1
+ynh_script_progression "Upgrading system configurations related to $app..."
 
-ynh_add_fpm_config
+ynh_config_add_phpfpm
 
-ynh_add_nginx_config
+ynh_config_add_nginx
 
 #=================================================
 # UPGRADE APPLICATION WITH CURL
 #=================================================
-ynh_script_progression --message="Upgrading Piwigo with cURL..." --weight=6
+ynh_script_progression "Upgrading Piwigo with cURL..."
 
 # Upgrade Piwigo via cURL
 # Why can't we trigger the migration from the command line somehow ...
@@ -53,24 +57,23 @@ ynh_local_curl "/upgrade.php?language=$language&now=true" "language=$language" "
 #=================================================
 # CONFIGURE PIWIGO
 #=================================================
-ynh_script_progression --message="Configuring $app..." --weight=2
+ynh_script_progression "Configuring $app..."
 
 # Change local config
-ynh_add_config --template="config.inc.php" --destination="$install_dir/local/config/config.inc.php"
+ynh_config_add --template="config.inc.php" --destination="$install_dir/local/config/config.inc.php"
 
 # Setup database in local/config/database.inc.php
-ynh_add_config --template="database.inc.php" --destination="$install_dir/local/config/database.inc.php"
+ynh_config_add --template="database.inc.php" --destination="$install_dir/local/config/database.inc.php"
 
-chmod -R o-rwx "$install_dir"
-chown -R "$app:www-data" "$install_dir"
-
+#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
+#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
 #=================================================
 # CONFIGURE LDAP PLUGIN
 #=================================================
-ynh_script_progression --message="Configuring LDAP plugin..." --weight=2
+ynh_script_progression "Configuring LDAP plugin..."
 
 # Disable LDAP plugin to avoid warning messages during API call
-ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" <<< "DELETE FROM plugins WHERE id='Ldap_Login';"
+ynh_mysql_db_shell <<< "DELETE FROM plugins WHERE id='Ldap_Login';"
 
 # Activate the LDAP plugin using the WS API
 
@@ -90,7 +93,7 @@ ynh_local_curl "/ws.php?format=json" "method=pwg.plugins.performAction" "action=
 ynh_local_curl "/ws.php?format=json" "method=pwg.session.logout"
 
 # Edit Ldap_Login plugin configuration
-ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" <<< "UPDATE ldap_login_config SET value='ou=users,dc=yunohost,dc=org' WHERE param = 'ld_basedn';
+ynh_mysql_db_shell <<< "UPDATE ldap_login_config SET value='ou=users,dc=yunohost,dc=org' WHERE param = 'ld_basedn';
 UPDATE ldap_login_config SET value='uid' WHERE param = 'ld_user_attr';
 UPDATE ldap_login_config SET value='' WHERE param = 'ld_binddn';
 UPDATE ldap_login_config SET value='0' WHERE param = 'allow_new_users';
@@ -98,29 +101,29 @@ UPDATE ldap_login_config SET value='0' WHERE param = 'ld_group_user_active';"
 
 # Remove configuration file for older plugin version
 if [ -f "$install_dir/plugins/Ldap_Login/data.dat" ] ; then
-    ynh_secure_remove --file="$install_dir/plugins/Ldap_Login/data.dat"
+    ynh_safe_rm "$install_dir/plugins/Ldap_Login/data.dat"
 fi
 
 #=================================================
 # UPGRADE FAIL2BAN
 #=================================================
-ynh_script_progression --message="Reconfiguring Fail2Ban..." --weight=8
+ynh_script_progression "Reconfiguring Fail2Ban..."
 
 # Configure and activate log_failed_logins plugin
-if ! ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" <<< "INSERT INTO plugins (id,state,version) VALUES ('log_failed_logins','active','1.2');" 2>&1 > /dev/null; then
-    ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" <<< "UPDATE plugins SET state='active' WHERE id='log_failed_logins';"
+if ! ynh_mysql_db_shell <<< "INSERT INTO plugins (id,state,version) VALUES ('log_failed_logins','active','1.2');" 2>&1 > /dev/null; then
+    ynh_mysql_db_shell <<< "UPDATE plugins SET state='active' WHERE id='log_failed_logins';"
 fi
-if ! ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" <<< "INSERT INTO config (param, value) VALUES ('logFailedLoginsFilename','/var/log/${app}FailedLogins.log');" 2>&1 > /dev/null; then
-    ynh_mysql_connect_as --user="$db_name" --password="$db_pwd" --database="$db_name" <<< "UPDATE config SET value='/var/log/${app}FailedLogins.log' WHERE param='logFailedLoginsFilename';"
+if ! ynh_mysql_db_shell <<< "INSERT INTO config (param, value) VALUES ('logFailedLoginsFilename','/var/log/${app}FailedLogins.log');" 2>&1 > /dev/null; then
+    ynh_mysql_db_shell <<< "UPDATE config SET value='/var/log/${app}FailedLogins.log' WHERE param='logFailedLoginsFilename';"
 fi
 
 touch "/var/log/${app}FailedLogins.log"
 chown "$app:" "/var/log/${app}FailedLogins.log"
 
-ynh_add_fail2ban_config --logpath="/var/log/${app}FailedLogins.log" --failregex="ip=<HOST>" --max_retry=6
+ynh_config_add_fail2ban --logpath="/var/log/${app}FailedLogins.log" --failregex="ip=<HOST>"
 
 #=================================================
 # END OF SCRIPT
 #=================================================
 
-ynh_script_progression --message="Upgrade of $app completed" --last
+ynh_script_progression "Upgrade of $app completed"
