Update upgrade

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -109,10 +109,10 @@ ynh_script_progression "Reconfiguring Fail2Ban..."
 
 # Configure and activate log_failed_logins plugin
 if ! ynh_mysql_db_shell <<< "INSERT INTO plugins (id,state,version) VALUES ('piwigo_failed_logins','active','1.1.1');" 2>&1 > /dev/null; then
-    ynh_mysql_db_shell <<< "UPDATE plugins SET state='active' WHERE id='log_failed_logins';"
+    ynh_mysql_db_shell <<< "UPDATE plugins SET state='active' WHERE id='piwigo_failed_logins';"
 fi
-if ! ynh_mysql_db_shell <<< "INSERT INTO config (param, value) VALUES ('logFailedLoginsFilename','/var/log/${app}FailedLogins.log');" 2>&1 > /dev/null; then
-    ynh_mysql_db_shell <<< "UPDATE config SET value='/var/log/${app}FailedLogins.log' WHERE param='logFailedLoginsFilename';"
+if ! ynh_mysql_db_shell <<< "INSERT INTO config (param, value) VALUES ('failed_logins_logfile','/var/log/${app}FailedLogins.log');" 2>&1 > /dev/null; then
+    ynh_mysql_db_shell <<< "UPDATE config SET value='/var/log/${app}FailedLogins.log' WHERE param='failed_logins_logfile';"
 fi
 
 touch "/var/log/${app}FailedLogins.log"
